GET http://localhost:3000/notes HTTP/1.1
authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvdXB1cHUiLCJpZCI6MywiaWF0IjoxNTc5NTkyNzM4fQ.4hjXeAGQPflm1fyCd770-okW52PAGbOqBauZ3MB1Cwk
content-type: application/json
